# Generated by Django 5.1.6 on 2025-04-09 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notification',
            name='object_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('blocked', 'Blocked'), ('no guardian', 'No_guardian')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='villager',
            name='approve_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_villagers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='villager',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_support_relation',
            name='support_role',
            field=models.CharField(choices=[('academic', 'Academic'), ('family', 'Family'), ('college', 'College'), ('trade_school', 'Trade School'), ('workforce_recruiter', 'Workforce Recruiter'), ('health_advisor', 'Health Advisor'), ('religion_advisor', 'Religion Advisor'), ('close_friend', 'Close Friend'), ('mentor', 'Mentor'), ('guardian', 'Guardian')], max_length=50),
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('support_role', models.CharField(max_length=50)),
                ('approval_status', models.CharField(choices=[('Pending', 'Pending'), ('approved', 'Approved'), ('Blocked', 'Blocked'), ('Accepted', 'User_accepted'), ('User reject', 'User_rejected')], default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests_received', to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.village')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationHistory',
            fields=[
                ('history_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.notification')),
            ],
        ),
    ]
