# Generated by Django 5.1.6 on 2025-03-29 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_village_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='village',
            name='temp',
        ),
    ]
