# Generated by Django 5.1.6 on 2025-03-30 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_id'),
        ('api', '0003_remove_village_temp'),
    ]

    operations = [
    ]
